In [3]:
from gensim.models import Word2Vec
import numpy as np

In [2]:
pip install gensim


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 62.1 MB/s eta 0:00:00


In [27]:
from gensim.models import Word2Vec
import numpy as np

sentences = [
    ["the", "cat", "drinks", "milk"],
    ["the", "dog", "drinks", "milk"],
    ["the", "cat", "is", "an", "animal"],
    ["the", "dog", "is", "an", "animal"]
]

model = Word2Vec(
    sentences,
    vector_size=100,
    window=2,
    min_count=1,
    sg=1
)

sentence = "the cat drinks milk"
words = sentence.lower().split()

for word in words:
    print(word)
    print(model.wv[word])

the
[-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.6826881e-03
 -1.5080082e-03  2.4

In [28]:
#Most raw idea of self attention is implemented below

In [29]:
from gensim.models import Word2Vec
import numpy as np

In [31]:
words=["apple a day keeps a doctor away","apple is a very expensive company","river bank has lot of water","milk bank is filled with milk","money bank has money"]

In [33]:
l=[]

In [35]:
for w in words:
  l.append(w.split())

In [36]:
l

[['apple', 'a', 'day', 'keeps', 'a', 'doctor', 'away'],
 ['apple', 'is', 'a', 'very', 'expensive', 'company'],
 ['river', 'bank', 'has', 'lot', 'of', 'water'],
 ['milk', 'bank', 'is', 'filled', 'with', 'milk'],
 ['money', 'bank', 'has', 'money']]

In [37]:
model = Word2Vec(
    l,
    vector_size=100,
    window=2,
    min_count=1,
    sg=1
)

In [53]:
sen1="apple is very expensive"

In [54]:
sen2="apple keeps doctor away"

In [55]:
sen1=sen1.split()
sen2=sen2.split()

In [56]:
soft=0
soft2=0

In [57]:
for w in sen1:
  soft=soft+np.exp(model.wv[sen1[0]]*model.wv[w])

In [58]:
for w in sen2:
  soft2=soft2+np.exp(model.wv[sen2[0]]*model.wv[w])

In [60]:
emb1=0

In [61]:
for w in sen1:
  emb1=emb1+(model.wv['apple']*(np.exp(model.wv['apple']*model.wv[w]))/soft)

In [62]:
emb2=0

In [64]:
for w in sen2:
  emb2=emb2+(model.wv['apple']*(np.exp(model.wv['apple']*model.wv[w]))/soft2)

In [65]:
emb1,emb2

(array([ 8.1322724e-03, -4.4573341e-03, -1.0683573e-03,  1.0063648e-03,
        -1.9111397e-04,  1.1481775e-03,  6.1138608e-03, -2.0271538e-05,
        -3.2459651e-03, -1.5107285e-03,  5.8972989e-03,  1.5141022e-03,
        -7.2426198e-04,  9.3332473e-03, -4.9212840e-03, -8.3840970e-04,
         9.1754114e-03,  6.7494274e-03,  1.5028560e-03, -8.8825608e-03,
         1.1487461e-03, -2.2882556e-03,  9.3682380e-03,  1.2099278e-03,
         1.4900637e-03,  2.4064099e-03, -1.8360066e-03, -4.9996334e-03,
         2.3242949e-04, -2.0141802e-03,  6.6009331e-03,  8.9401230e-03,
        -6.7475432e-04,  2.9770148e-03, -6.1076549e-03,  1.6993249e-03,
        -6.9262329e-03, -8.6940266e-03, -5.9002033e-03, -8.9564752e-03,
         7.2775944e-03, -5.7720314e-03,  8.2763508e-03, -7.2435448e-03,
         3.4216749e-03,  9.6749999e-03, -7.7854479e-03, -9.9450573e-03,
        -4.3291468e-03, -2.6831306e-03, -2.7128935e-04, -8.8315513e-03,
        -8.6175576e-03,  2.8002108e-03, -8.2064057e-03, -9.06933

In [66]:
np.dot(emb1,emb2)

np.float32(0.0061551556)

In [67]:
#For parallelism

In [68]:
matrix=[]

In [69]:
for w in sen1:
  matrix.append(model.wv[w])


In [70]:
matrix

[array([ 8.13227147e-03, -4.45733406e-03, -1.06835726e-03,  1.00636482e-03,
        -1.91113955e-04,  1.14817743e-03,  6.11386076e-03, -2.02715401e-05,
        -3.24596534e-03, -1.51072862e-03,  5.89729892e-03,  1.51410222e-03,
        -7.24261976e-04,  9.33324732e-03, -4.92128357e-03, -8.38409644e-04,
         9.17541143e-03,  6.74942741e-03,  1.50285603e-03, -8.88256077e-03,
         1.14874600e-03, -2.28825561e-03,  9.36823711e-03,  1.20992784e-03,
         1.49006362e-03,  2.40640994e-03, -1.83600665e-03, -4.99963388e-03,
         2.32429506e-04, -2.01418041e-03,  6.60093315e-03,  8.94012302e-03,
        -6.74754381e-04,  2.97701475e-03, -6.10765442e-03,  1.69932481e-03,
        -6.92623248e-03, -8.69402662e-03, -5.90020278e-03, -8.95647518e-03,
         7.27759488e-03, -5.77203138e-03,  8.27635173e-03, -7.24354526e-03,
         3.42167495e-03,  9.67499893e-03, -7.78544787e-03, -9.94505733e-03,
        -4.32914635e-03, -2.68313056e-03, -2.71289347e-04, -8.83155130e-03,
        -8.6

In [72]:
matrix=np.array(matrix)

In [73]:
matrix

array([[ 8.13227147e-03, -4.45733406e-03, -1.06835726e-03,
         1.00636482e-03, -1.91113955e-04,  1.14817743e-03,
         6.11386076e-03, -2.02715401e-05, -3.24596534e-03,
        -1.51072862e-03,  5.89729892e-03,  1.51410222e-03,
        -7.24261976e-04,  9.33324732e-03, -4.92128357e-03,
        -8.38409644e-04,  9.17541143e-03,  6.74942741e-03,
         1.50285603e-03, -8.88256077e-03,  1.14874600e-03,
        -2.28825561e-03,  9.36823711e-03,  1.20992784e-03,
         1.49006362e-03,  2.40640994e-03, -1.83600665e-03,
        -4.99963388e-03,  2.32429506e-04, -2.01418041e-03,
         6.60093315e-03,  8.94012302e-03, -6.74754381e-04,
         2.97701475e-03, -6.10765442e-03,  1.69932481e-03,
        -6.92623248e-03, -8.69402662e-03, -5.90020278e-03,
        -8.95647518e-03,  7.27759488e-03, -5.77203138e-03,
         8.27635173e-03, -7.24354526e-03,  3.42167495e-03,
         9.67499893e-03, -7.78544787e-03, -9.94505733e-03,
        -4.32914635e-03, -2.68313056e-03, -2.71289347e-0

In [74]:
matrix.shape

(4, 100)

In [75]:
coeff=matrix@matrix.T

In [76]:
import torch

In [77]:
coeff=torch.tensor(coeff)

In [79]:
coeff=torch.softmax(coeff,dim=1)

In [81]:
coeff.ndim

2

In [82]:
coeff.shape

torch.Size([4, 4])

In [83]:
coeff

tensor([[0.2506, 0.2499, 0.2497, 0.2498],
        [0.2498, 0.2508, 0.2498, 0.2497],
        [0.2497, 0.2498, 0.2508, 0.2497],
        [0.2498, 0.2497, 0.2497, 0.2507]])

In [84]:
finalemb=coeff@torch.tensor(matrix)

In [86]:
finalemb[0]

tensor([-1.4936e-05,  2.7508e-03,  3.3915e-04, -2.2986e-03, -1.5200e-03,
        -2.1284e-03,  2.5514e-03,  2.8424e-03, -1.1391e-03, -2.2906e-03,
         1.4593e-03, -4.7853e-03, -4.9221e-03, -7.3285e-04, -4.8964e-03,
        -1.7720e-03,  1.2567e-03,  9.4731e-04,  1.5597e-03, -2.8474e-03,
        -7.6463e-04,  2.2153e-03,  2.8490e-03,  8.2395e-04, -4.7270e-03,
         6.3065e-04,  1.7697e-04, -2.1773e-03,  2.4052e-03, -2.0274e-03,
        -5.5284e-04, -2.2296e-03, -5.9325e-04, -5.8500e-04, -4.3425e-03,
         2.6802e-03,  4.1940e-03, -8.2229e-04, -2.5070e-03,  1.1513e-03,
         8.2883e-03, -4.6511e-03,  2.2947e-04,  5.1853e-04,  2.8709e-03,
         5.4543e-03, -5.1741e-03, -3.5461e-03, -6.4740e-04, -2.4683e-03,
         2.2277e-04, -3.8930e-03,  3.3515e-03,  2.8792e-03, -5.9548e-03,
        -2.0147e-03,  6.3639e-03, -3.3924e-03, -1.0860e-03, -1.2218e-03,
         6.1836e-04, -3.8483e-03,  3.4456e-03, -7.8469e-04,  3.0541e-03,
         2.1472e-03, -2.5461e-03,  8.7405e-04, -2.7

In [87]:
emb1

array([ 8.1322724e-03, -4.4573341e-03, -1.0683573e-03,  1.0063648e-03,
       -1.9111397e-04,  1.1481775e-03,  6.1138608e-03, -2.0271538e-05,
       -3.2459651e-03, -1.5107285e-03,  5.8972989e-03,  1.5141022e-03,
       -7.2426198e-04,  9.3332473e-03, -4.9212840e-03, -8.3840970e-04,
        9.1754114e-03,  6.7494274e-03,  1.5028560e-03, -8.8825608e-03,
        1.1487461e-03, -2.2882556e-03,  9.3682380e-03,  1.2099278e-03,
        1.4900637e-03,  2.4064099e-03, -1.8360066e-03, -4.9996334e-03,
        2.3242949e-04, -2.0141802e-03,  6.6009331e-03,  8.9401230e-03,
       -6.7475432e-04,  2.9770148e-03, -6.1076549e-03,  1.6993249e-03,
       -6.9262329e-03, -8.6940266e-03, -5.9002033e-03, -8.9564752e-03,
        7.2775944e-03, -5.7720314e-03,  8.2763508e-03, -7.2435448e-03,
        3.4216749e-03,  9.6749999e-03, -7.7854479e-03, -9.9450573e-03,
       -4.3291468e-03, -2.6831306e-03, -2.7128935e-04, -8.8315513e-03,
       -8.6175576e-03,  2.8002108e-03, -8.2064057e-03, -9.0693356e-03,
      

In [4]:
pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 64.8 MB/s eta 0:00:00


In [5]:
import torch
import gensim
from gensim.models import Word2Vec
import numpy as np

In [7]:
from torch import nn

In [47]:
#Wrote the below code on my own, no reference, was able to realise one thing that was
#We can write the entire thing of passing embeddings using nerual networks itself.
#Though using nn.Params is also fine not as issue, but yeah a good intuition build up of how we can do this as well was new learning.

In [9]:
sent=["Hello there, I am Sai","Nice to meet you", "You are a good person", "May god bless you", "Do you have an apple", "Do you like grapes"]

In [10]:
l=[]

In [11]:
for w in sent:
  l.append(w.split())

In [12]:
l

[['Hello', 'there,', 'I', 'am', 'Sai'],
 ['Nice', 'to', 'meet', 'you'],
 ['You', 'are', 'a', 'good', 'person'],
 ['May', 'god', 'bless', 'you'],
 ['Do', 'you', 'have', 'an', 'apple'],
 ['Do', 'you', 'like', 'grapes']]

In [16]:
model=Word2Vec(
    l,
    vector_size=100,
    window=2,
    min_count=1,
    sg=1
)

In [19]:
sent=["Hello there, I am Sai","Nice to meet you", "You are a good person"]

In [20]:
s=[]

In [21]:
for w in sent:
  s.append(w.split())

In [22]:
s

[['Hello', 'there,', 'I', 'am', 'Sai'],
 ['Nice', 'to', 'meet', 'you'],
 ['You', 'are', 'a', 'good', 'person']]

In [23]:
finalemb=[]
for w in s:
  finalemb.append(model.wv[w])

In [29]:
import torch
from torch.nn.utils.rnn import pad_sequence

In [31]:
finalemb = [torch.tensor(x) for x in finalemb]

In [32]:
padded = pad_sequence(
    finalemb,
    batch_first=True,
    padding_value=0.0
)

In [33]:
padded

tensor([[[-2.3749e-04,  4.2192e-03,  2.1141e-03,  ...,  7.6671e-05,
          -5.9593e-06,  8.7101e-03],
         [ 1.3357e-03,  6.5436e-03,  9.9855e-03,  ...,  9.0615e-03,
          -5.7933e-03,  3.6875e-03],
         [ 2.5726e-03,  8.4812e-04, -2.5383e-03,  ..., -1.6652e-03,
          -9.4556e-03, -2.6127e-03],
         [ 5.6267e-03,  5.4974e-03,  1.8291e-03,  ...,  7.3133e-03,
           5.4656e-03,  9.2495e-03],
         [ 9.7355e-03, -9.7804e-03, -6.4995e-03,  ..., -2.7012e-03,
           3.8248e-03,  3.3762e-04]],

        [[ 1.8002e-03,  7.0461e-03,  2.9447e-03,  ..., -1.8596e-03,
           3.6117e-03, -7.0364e-03],
         [ 1.3002e-03, -9.8043e-03,  4.5878e-03,  ..., -2.5876e-03,
          -7.7572e-03,  4.1926e-03],
         [-7.1909e-03,  4.2329e-03,  2.1634e-03,  ...,  9.4381e-03,
           7.0553e-03,  6.7550e-03],
         [-5.3577e-04,  2.3608e-04,  5.1046e-03,  ..., -7.0416e-03,
           9.0212e-04,  6.3926e-03],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...

In [56]:
sa=SelfAttention(embed_size=100,heads=10)

In [57]:
padded

tensor([[[-2.3749e-04,  4.2192e-03,  2.1141e-03,  ...,  7.6671e-05,
          -5.9593e-06,  8.7101e-03],
         [ 1.3357e-03,  6.5436e-03,  9.9855e-03,  ...,  9.0615e-03,
          -5.7933e-03,  3.6875e-03],
         [ 2.5726e-03,  8.4812e-04, -2.5383e-03,  ..., -1.6652e-03,
          -9.4556e-03, -2.6127e-03],
         [ 5.6267e-03,  5.4974e-03,  1.8291e-03,  ...,  7.3133e-03,
           5.4656e-03,  9.2495e-03],
         [ 9.7355e-03, -9.7804e-03, -6.4995e-03,  ..., -2.7012e-03,
           3.8248e-03,  3.3762e-04]],

        [[ 1.8002e-03,  7.0461e-03,  2.9447e-03,  ..., -1.8596e-03,
           3.6117e-03, -7.0364e-03],
         [ 1.3002e-03, -9.8043e-03,  4.5878e-03,  ..., -2.5876e-03,
          -7.7572e-03,  4.1926e-03],
         [-7.1909e-03,  4.2329e-03,  2.1634e-03,  ...,  9.4381e-03,
           7.0553e-03,  6.7550e-03],
         [-5.3577e-04,  2.3608e-04,  5.1046e-03,  ..., -7.0416e-03,
           9.0212e-04,  6.3926e-03],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...

In [58]:
sa.forwardpass(padded[0])

The radomly allocated Q,K and V values are the following : tensor([[-4.9668e-02, -3.8618e-02, -5.3074e-02, -5.4605e-02, -4.3982e-02,
         -6.4658e-02, -3.5568e-02,  1.0306e-01,  7.4976e-03,  3.5066e-02,
          1.6997e-03,  9.1176e-03, -2.1880e-02, -5.0794e-02, -5.6049e-02,
          7.8813e-02,  6.3088e-02, -8.8119e-02, -9.6021e-02, -4.0723e-03,
          3.2295e-02,  2.2188e-03, -9.3334e-02,  7.9668e-02,  8.6109e-02,
         -3.5180e-02,  9.2236e-02,  2.1503e-03,  3.7819e-02,  5.6949e-02,
          2.0411e-02,  3.5179e-02,  6.1110e-02, -4.1948e-02,  4.4837e-02,
          8.6794e-02, -1.4243e-02, -7.5508e-02, -6.5943e-02, -1.3412e-03,
          3.0979e-02,  5.6337e-03, -9.5992e-03, -7.3025e-02,  2.1791e-03,
          7.3542e-02,  7.0859e-03, -7.2487e-02, -1.3193e-02, -9.7407e-02,
         -7.5387e-02,  4.7984e-02, -9.4258e-02, -4.6562e-02, -5.2213e-02,
         -7.1616e-02, -8.6072e-03,  8.0281e-02,  8.5108e-02, -2.3185e-02,
          2.0720e-02, -2.0884e-02,  1.2796e-02, -4.23

In [59]:
sa.coeff()

The coeff or the final weights we get to multiply are:tensor([[0.1994, 0.2002, 0.2007, 0.1995, 0.2003],
        [0.1994, 0.2002, 0.2006, 0.1995, 0.2003],
        [0.1994, 0.2002, 0.2006, 0.1995, 0.2004],
        [0.1994, 0.2002, 0.2006, 0.1995, 0.2003],
        [0.1994, 0.2002, 0.2006, 0.1995, 0.2003]], grad_fn=<SoftmaxBackward0>)


In [60]:
sa.finalemb()

The final embedding is:tensor([[ 0.0304, -0.0464,  0.0460,  0.0730,  0.0533,  0.0147,  0.0393, -0.0230,
          0.0405, -0.0150,  0.0940,  0.0680, -0.0981,  0.0237, -0.0637,  0.0601,
          0.0005, -0.0387,  0.0361,  0.0459, -0.0880,  0.0210,  0.0327,  0.0779,
          0.0024, -0.0835, -0.0500,  0.0652,  0.0618, -0.0818,  0.0869, -0.0513,
         -0.0508,  0.0192,  0.0948,  0.0204, -0.0356, -0.0292,  0.0388,  0.0356,
         -0.0803, -0.0335, -0.0280, -0.0257,  0.0024, -0.0559, -0.0112, -0.0317,
          0.0988,  0.0206,  0.0856,  0.0728, -0.0102, -0.0294,  0.0875, -0.0603,
         -0.0328, -0.0977,  0.0477, -0.0514,  0.0684, -0.0273, -0.0519,  0.0998,
          0.0066,  0.0837,  0.0856,  0.0816,  0.0122,  0.0107, -0.0705, -0.0913,
         -0.0087,  0.0332, -0.0373, -0.0560, -0.0564, -0.0392, -0.0975, -0.0652,
         -0.0447, -0.0051, -0.0700,  0.0153, -0.0360,  0.0468, -0.0566, -0.0447,
         -0.0603,  0.0944,  0.0307,  0.0976,  0.0935, -0.0372, -0.0860,  0.0978,
     

In [66]:
import random

In [68]:
random.seed(18)

In [61]:
#Now I would proceed to Multi-head attention

In [62]:
#In multi-head attention there is not much of things to do except the fact that we have to have multiple SA blocks.

In [79]:
class SelfAttention(nn.Module):
  def __init__(self,embed_size,heads):
    super().__init__()
    self.embed_size=embed_size
    self.Q=nn.Linear(embed_size,embed_size)
    self.K=nn.Linear(embed_size,embed_size)
    self.V=nn.Linear(embed_size,embed_size)
  def forwardpass(self,embedding):
    self.q=self.Q(embedding)
    self.k=self.K(embedding)
    self.v=self.V(embedding)
    print(f"The radomly allocated Q,K and V values are the following : {self.q},{self.k},{self.v}")
  def coeff(self):
    self.coeff=torch.softmax(self.q@self.k.T,dim=1)
    print(f"The coeff or the final weights we get to multiply are:{self.coeff}")
  def finalemb(self):
    self.finalemb=self.coeff@self.v
    print(f"The final embedding is:{self.finalemb}")


In [87]:
class MultiHeadAttention(nn.Module):
  def __init__(self,embed_size,heads):
    super().__init__()
    self.embed_size=embed_size
    self.heads=heads
    self.sa=[]
    for i in range(heads):
      self.sa.append(SelfAttention(embed_size,heads))
  def forward(self,embedding):
    for i in range(self.heads):
      self.sa[i].forwardpass(embedding)
  def coeffs(self):
    for i in range(self.heads):
      self.sa[i].coeff()
  def finalembs(self):
    for i in range(self.heads):
      self.sa[i].finalemb()

In [88]:
MHA=MultiHeadAttention(embed_size=100,heads=2)

In [89]:
MHA

MultiHeadAttention()

In [90]:
MHA.forward(padded[0])

The radomly allocated Q,K and V values are the following : tensor([[ 0.0140, -0.0158, -0.0687,  0.0527, -0.0468,  0.0497, -0.0639,  0.0885,
         -0.0395,  0.0334, -0.0443,  0.0919, -0.0538,  0.0680, -0.0242,  0.0238,
         -0.0858, -0.0325, -0.0556, -0.0413,  0.0763,  0.0451,  0.0364,  0.0636,
          0.1011,  0.0196,  0.0896,  0.0311, -0.0341,  0.0354,  0.0124, -0.0266,
         -0.0281,  0.0744, -0.0757,  0.0085,  0.0763, -0.0662,  0.0344,  0.0479,
         -0.0473, -0.0340, -0.0430, -0.0247,  0.0597, -0.0860, -0.0234, -0.0772,
          0.0761,  0.0023,  0.0350,  0.0712,  0.0249,  0.0134, -0.0753, -0.0498,
          0.0321, -0.0798,  0.0626,  0.0247,  0.0617,  0.0149,  0.0685, -0.0322,
         -0.0718,  0.0911, -0.0372, -0.1004,  0.0095, -0.0387,  0.0097,  0.0693,
         -0.0136, -0.0083,  0.0513, -0.0284,  0.0628,  0.0969,  0.0898,  0.0734,
          0.0242,  0.0642, -0.0505, -0.0573, -0.0608,  0.0378, -0.0946, -0.0977,
         -0.0075, -0.0385,  0.0940,  0.0583,  0.00

In [92]:
MHA.coeffs()

The coeff or the final weights we get to multiply are:tensor([[0.1998, 0.2002, 0.1996, 0.2003, 0.2000],
        [0.1998, 0.2003, 0.1996, 0.2003, 0.2000],
        [0.1998, 0.2002, 0.1996, 0.2003, 0.2000],
        [0.1998, 0.2003, 0.1996, 0.2004, 0.2000],
        [0.1998, 0.2002, 0.1996, 0.2003, 0.2000]], grad_fn=<SoftmaxBackward0>)
The coeff or the final weights we get to multiply are:tensor([[0.1997, 0.1997, 0.2002, 0.2001, 0.2002],
        [0.1998, 0.1997, 0.2002, 0.2001, 0.2001],
        [0.1998, 0.1997, 0.2002, 0.2002, 0.2001],
        [0.1998, 0.1997, 0.2002, 0.2002, 0.2001],
        [0.1997, 0.1998, 0.2002, 0.2002, 0.2001]], grad_fn=<SoftmaxBackward0>)


In [93]:
MHA.finalembs()

The final embedding is:tensor([[-0.0650, -0.0271,  0.0459,  0.0248,  0.0110, -0.0318,  0.0602,  0.0706,
          0.0757,  0.0744,  0.0420, -0.0270, -0.0423,  0.0032,  0.0927,  0.0577,
         -0.0028,  0.0626, -0.0070,  0.0494, -0.0025,  0.0855, -0.0410, -0.0831,
          0.0265,  0.0141, -0.0913, -0.0388,  0.0464,  0.0679,  0.0789,  0.0888,
         -0.0012,  0.0634, -0.0990, -0.0569,  0.0447, -0.0548, -0.0278,  0.0691,
          0.0006, -0.0367,  0.0743, -0.0594,  0.0618, -0.0845, -0.0063,  0.0675,
          0.0106, -0.0452, -0.0818,  0.0488, -0.0625,  0.0912,  0.0401,  0.0490,
          0.0874,  0.0635, -0.1009,  0.0993, -0.0445, -0.0215,  0.0896,  0.0597,
          0.0201, -0.0184,  0.0028, -0.0671, -0.0534, -0.0170, -0.0249,  0.0081,
         -0.0882,  0.0804,  0.0375,  0.0091, -0.0447, -0.0897, -0.0987, -0.0770,
         -0.0246,  0.0404,  0.0184,  0.0436, -0.0344,  0.0416,  0.0505,  0.0661,
          0.0538,  0.0785,  0.0761,  0.0708,  0.0763,  0.0474, -0.0218,  0.0217,
     